import {StyleSheet} from 'react-native';
import {widthPercentageToDP as wp} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  auditTitleContainer: {
    display: 'flex',
    flexDirection: 'column',
    margin: 16,
    borderColor: '#EDEEF1',
    boxShadow: '0px 2px 12px 0px rgba(10, 10, 10, 0.10)',
    borderRadius: 6,
    fontFamily: 'Roboto',
  },
  titleTop: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomColor: '#E6E6E6',
    borderBottomWidth: 1,
  },
  titleBottom: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  auditFieldName: {
    color: '#848B98',
    fontFamily: 'Roboto',
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0.6,
  },
  auditName: {
    color: '#3B475B',
    fontFamily: 'Roboto',
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 0.9,
    textTransform: 'capitalize',
  },
  auditField: {
    color: '#848B98',
    fontFamily: 'Roboto',
    fontSize: 10,
    fontWeight: 400,
    lineHeight: 13,
    letterSpacing: 0.5,
    textTransform: 'capitalize',
  },
  auditValue: {
    color: '#3B475B',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.6,
    lineHeight: 15.5,
  },
  auditDetail: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  progressContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  progressDisplay: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressText: {
    color: '#848B98',
    fontFamily: 'Roboto',
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: 0.5,
    textTransform: 'capitalize',
  },
  progressBlue: {
    color: '#1E90FF',
    fontFamily: 'Roboto',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.8,
    textTransform: 'capitalize',
  },
  progressGray: {
    color: '#8D8D8D',
    fontFamily: 'Roboto',
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0.6,
    textTransform: 'capitalize',
  },
  progressDataList: {
    display: 'flex',
    flexDirection: 'row',
    gap: 24,
  },
  progressDataDisplay: {
    display: 'flex',
    flexDirection: 'column',
    padding: 8,
    gap: 8,
    backgroundColor: '#F9F9F9',
    boxShadow: '1px 1px 16px 0px rgba(0, 0, 0, 0.12)',
    flexGrow: 1,
    alignItems: 'center',
  },
  progressDataTitle: {
    color: '#8A8A8A',
    fontFamily: 'Roboto',
    fontSize: 10,
    lineHeight: 13,
    letterSpacing: 0.5,
    textTransform: 'capitalize',
  },
  progressDataValue: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  assetLists: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: 4,
    justifyContent: 'space-between',
  },
  assetListsTitle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E6E6E6',
    borderTopWidth: 1,
    borderTopColor: '#E6E6E6',
  },
  assetListTitleText: {
    color: '#3B475B',
    fontFamily: 'Roboto',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.6,
  },
  search: {
    borderWidth: 0,
    color: '#3B475B',
    maxWidth: 200,
    width: 160,
    fontSize: 9,
    letterSpacing: 0.135,
    textAlignVertical: 'center',
    lineHeight: 12,
    padding: 0,
    margin: 0,
  },
  searchbar: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#E6E6E6',
    borderWidth: 0.75,
    borderRadius: 12,
    paddingHorizontal: 8,
    padding: 0,
    gap: 8,
    height: 24,
  },
  assetDetailItem: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E6E6E6',
    alignItems: 'center',
  },
  assetItemList: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: 8,
    flexGrow: 1,
    height: 40,
  },
  assetItemDetail: {
    display: 'flex',
    flexDirection: 'column',
  },
  assetIdText: {
    color: '#3B475B',
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.7,
    fontFamily: 'Roboto',
  },
  assetNameText: {
    color: '#848B98',
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0.6,
    fontFamily: 'Roboto',
  },
  assetStatus: {
    fontFamily: 'Roboto',
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0.18,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  bottomFooter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    gap: 16,
    boxShadow: '0px -4px 12px 0px rgba(0, 0, 0, 0.12)',
  },
  cancelBtn: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#8C8C8C',
    boxShadow: '0px 1px 2px 0px rgba(27, 32, 41, 0.05);',
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitBtn: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 12,
    boxShadow: '0px 1px 2px 0px rgba(27, 32, 41, 0.05);',
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E90FF',
  },
  submit: {
    color: '#FAFBFF',
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.7,
    lineHeight: 18.2,
  },
  cancel: {
    color: '#1D232F',
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.7,
    lineHeight: 18.2,
  },
  noRecord: {
    fontSize: wp(3.5),
    letterSpacing: wp(0.15),
    padding: 12,
    color: '#848B98',
    textAlign: 'center',
  },
});

export default styles;
