import {StyleSheet} from 'react-native';
import {widthPercentageToDP as wp} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  assetDataCard: {
    width: wp(90),
    backgroundColor: '#FBFDFF',
    margin: wp(5),
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F1F1F1',
    elevation: 12,
  },
  assetInfoContainer: {
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: wp(4),
    paddingVertical: wp(6),
    paddingTop: wp(5),
    gap: wp(4),
    justifyContent: 'space-between',
  },
  assetInfoCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D4E2F0',
    borderRadius: 8,
    paddingHorizontal: wp(3),
    gap: wp(3),
    flexDirection: 'row',
    paddingVertical: wp(2.5),
    alignItems: 'center',
  },
  selectLocation: {
    borderColor: '#D4E2F0',
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: '#EAF1F7',
    marginHorizontal: wp(4),
    marginVertical: wp(6),
    marginBottom: wp(5),
    padding: wp(3),
    paddingRight: wp(4),
  },
  selectLocationPlaceholder: {
    fontSize: wp(4),
    fontWeight: '600',
    color: '#768997',
  },
  selectLocationText: {
    fontSize: wp(4),
    fontWeight: '600',
    color: '#3B475B',
  },
  radioDot: {
    flex: 1,
    borderRadius: wp(100),
  },
  radioDotContainer: {
    borderWidth: wp(0.7),
    height: wp(6),
    width: wp(6),
    padding: wp(0.7),
    borderRadius: wp(100),
  },
  assetInfoValue: {
    fontSize: wp(3.5),
    fontWeight: '500',
    color: '#3B475B',
  },
  assetInfoTitle: {
    fontSize: wp(3.5),
    fontWeight: '400',
    color: '#3B475B',
  },
  menuList: {
    display: 'flex',
    flexDirection: 'column',
    gap: wp(4),
    padding: wp(4),
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  menuButton: {
    backgroundColor: '#FBFDFF',
    padding: wp(5),
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F1F1F1',
    elevation: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  menuTitleContainer: {
    flexDirection: 'row',
    gap: wp(5),
  },
  menuTitle: {
    fontWeight: '500',
    fontSize: wp(4),
    color: '#3B475B',
  },
  footer: {
    borderWidth: 2,
    borderColor: '#F1F1F1',
  },
  backButton: {
    margin: wp(5),
    width: wp(90),
    padding: wp(3),
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#8C8C8C',
    borderWidth: 1.5,
    borderRadius: 8,
  },
  backButtonText: {
    color: '#1D232F',
    fontWeight: '600',
    fontSize: wp(4),
  },
  submitButton: {
    backgroundColor: '#1E90FF',
    borderColor: '#1E90FF',
  },
  submitButtonText: {
    color: '#FAFBFF',
    fontWeight: '600',
    fontSize: wp(4),
  },
  disabled: {
    backgroundColor: '#EEF1F4',
    borderColor: '#EEF1F4',
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    paddingBottom: 0,
  },
  drawerContainer: {
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: 20,
    paddingBottom: 0,
  },
  drawerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    color: '#3B475B',
    letterSpacing: 0.9,
  },
  drawerMessage: {
    fontSize: 14,
    color: '#848B98',
    fontFamily: 'Roboto',
    letterSpacing: 0.7,
  },
  drawerButtons: {
    flexDirection: 'row',
    padding: 16,
    display: 'flex',
    gap: 16,
  },
  drawerCancel: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    borderColor: '#8C8C8C',
  },
  drawerCancelText: {
    color: '#1D232F',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '500',
  },
  drawerSubmit: {
    backgroundColor: '#1E90FF',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    flex: 1,
  },
  drawerSubmitText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
  },
  search: {
    borderWidth: 0,
    color: '#3B475B',
    fontSize: 14,
    letterSpacing: 0.135,
    textAlignVertical: 'center',
    lineHeight: 12,
    padding: 0,
    margin: 0,
    flex: 1,
    height: 40,
  },
  searchbar: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#E6E6E6',
    borderWidth: 0.75,
    borderRadius: 12,
    padding: 20,
    flex: 1,
    gap: 8,
    marginHorizontal: 20,
    marginVertical: 0,
  },
});

export default styles;
